pontera_dwh:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: kub83756.us-east-1

      # User/password auth
      user: LIRAN
      password: rR2um5m6RjeQKsu

      role: DEVELOPER
      database: util_db
      warehouse: COMPUTE_WH
      schema: lcohen
      threads: 4
      client_session_keep_alive: False
      query_tag: anything

      # optional
      connect_retries: 0 # default 0
      connect_timeout: 10 # default: 10
      retry_on_database_errors: False # default: false
      retry_all: False  # default: false
      reuse_connections: False # default: false (available v1.4+)
    
    production:
      type: snowflake
      account: kub83756.us-east-1

      # User/password auth
      user: LIRAN
      password: rR2um5m6RjeQKsu

      role: DEVELOPER
      database: default
      warehouse: COMPUTE_WH
      schema: default
      threads: 4
      client_session_keep_alive: False
      query_tag: anything

      # optional
      connect_retries: 0 # default 0
      connect_timeout: 10 # default: 10
      retry_on_database_errors: False # default: false
      retry_all: False  # default: false
      reuse_connections: False # default: false (available v1.4+)



# Profile name should be the same as in dbt_project.yml
<PROFILE_NAME>:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: <SNOWFLAKE_HOST>

      # User/password auth
      user: <SNOWFLAKE_USERNAME>
      password: <SNOWFLAKE_PASSWORD>

      role: <SNOWFLAKE_ROLE>
      database: <SNOWFLAKE_DATABASE>
      warehouse: <SNOWFLAKE_WAREHOUSE>
      schema: <SCHEMA>
      threads: 4
      client_session_keep_alive: False
      query_tag: anything

      # optional
      connect_retries: 0 # default 0
      connect_timeout: 10 # default: 10
      retry_on_database_errors: False # default: false
      retry_all: False  # default: false
      reuse_connections: False # default: false (available v1.4+)
      
    production:
      type: snowflake
      account: <SNOWFLAKE_HOST>

      # User/password auth
      user: <SNOWFLAKE_USERNAME>
      password: <SNOWFLAKE_PASSWORD>

      role: <SNOWFLAKE_ROLE>
      database: <SNOWFLAKE_DATABASE>
      warehouse: <SNOWFLAKE_WAREHOUSE>
      schema: <SCHEMA>
      threads: 4
      client_session_keep_alive: False
      query_tag: anything

      # optional
      connect_retries: 0 # default 0
      connect_timeout: 10 # default: 10
      retry_on_database_errors: False # default: false
      retry_all: False  # default: false
      reuse_connections: False # default: false (available v1.4+)
